### ISSUE TITLE
Corrupt NuGet package for 1.1.1

### ISSUE THREAD

**Issue by ronaldbarendse** [motowilliams/T4-AppSettings#3]
After updating the NuGet package from 1.1.0 to 1.1.1, the T4 transform gives the following errors:

```
Compiling transformation: 'GeneratedTextTransformation.Write()' must declare a body because it is not marked abstract, extern, or partial
Compiling transformation: Identifier expected
Compiling transformation: Invalid token 'this' in class, struct, or interface member declaration
Compiling transformation: Method must have a return type
```

The only difference between these versions is the addition of a dash in the `CleanPropertyName` function **and** a trailing new line (after the `#>`). After removing the trailing white space, the T4 templated compiled again.

So please update the NuGet package with a working template (and update the nuspec file with the correct version!).

**Comment by motowilliams** [comment]
Fixed 8fec339cdf9d9b3b9a5c272a0adbf880ea937a50 and published to nuget https://www.nuget.org/packages/T4AppSettings/

Sorry for taking so long on this and thanks for the report.
